# run gitlab-ci local
# https://github.com/firecow/gitlab-ci-local

image: node:latest

stages:
  - code_quality
  - test
  # - deploy

sast:
  stage: code_quality
  include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  # https://docs.gitlab.com/ee/user/application_security/secret_detection/#enable-secret-detection
  - template: Jobs/Secret-Detection.gitlab-ci.yml

lint:
  stage: code_quality
  script:
    - yarn run lint

#sast_test:
#  stage: code_quality
#  image: node:latest
#  entrypoint: [""]
#  script:
#    - npm install -g snyk
#    - snyk test
#  tags:
#    - node
#  coverage: "/snyk-report.json"

security-scan:
  stage: code_quality
  image: node:latest
  script:
    - yarn install
    - yarn audit
    # - yarn audit fix

test-unit:
  stage: test
  script:
    - yarn install
    - yarn run test.unit

test-e2e:
  stage: test
  script:
    - yarn install
    - yarn run test.e2e

#deploy:
#  stage: deploy
#  script:
#    - yarn install
#    - yarn run deploy
